include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_TASK_LAB_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_TASK_LAB_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_TASK_LAB_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_TASK_LAB)

MAINSRC = task_lab_main.c

include $(APPDIR)/Application.mk
